# Generated by Django 4.2.1 on 2024-05-01 22:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tayangan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('sinopsis', models.CharField(max_length=255)),
                ('asal_negara', models.CharField(max_length=50)),
                ('sinopsis_trailer', models.CharField(max_length=255)),
                ('url_video_trailer', models.CharField(max_length=255)),
                ('release_date_trailer', models.DateField()),
            ],
            options={
                'db_table': 'TAYANGAN',
            },
        ),
    ]
