# Generated by Django 4.2.1 on 2024-05-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tayangan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tayangan',
        ),
    ]
